[program:ugclab-reverb]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/ugclab/backend/artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/ugclab/backend/storage/logs/supervisor-reverb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
